-- 코드를 입력하세요
SELECT TB1.AUTHOR_ID AS AUTHOR_ID, TB2.AUTHOR_NAME AS AUTHOR_NAME,
TB1.CATEGORY AS CATEGORY,
SUM((TB1.PRICE * TB3.SALES)) AS TOTAL_SALES
FROM BOOK TB1, AUTHOR TB2,BOOK_SALES TB3
WHERE TB1.AUTHOR_ID = TB2.AUTHOR_ID
AND TB1.BOOK_ID = TB3.BOOK_ID
AND YEAR(TB3.SALES_DATE) = 2022 
AND MONTH(TB3.SALES_DATE) = 1
GROUP BY TB2.AUTHOR_ID, TB1.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

