SELECT TB1.CAR_ID,TB1.CAR_TYPE,
ROUND(((100 - TB3.DISCOUNT_RATE) / 100) * TB1.DAILY_FEE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR TB1, CAR_RENTAL_COMPANY_RENTAL_HISTORY TB2,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN TB3
WHERE TB1.CAR_ID = TB2.CAR_ID
AND TB1.CAR_TYPE = TB3.CAR_TYPE
AND TB3.DURATION_TYPE LIKE '30%'
AND TB1.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE START_DATE <'2022-12-01' AND END_DATE > '2022-11-01')
                      # 서브쿼리에는 대여불가능한걸 넣어야한다
GROUP BY TB2.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC
