-- 코드를 입력하세요
SELECT TB1.CAR_ID,TB1.CAR_TYPE,
ROUND((100 - TB3.DISCOUNT_RATE) / 100 * (TB1.DAILY_FEE * 30)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR TB1, CAR_RENTAL_COMPANY_RENTAL_HISTORY TB2,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN TB3
WHERE TB1.CAR_ID = TB2.CAR_ID # JOIN
AND TB1.CAR_TYPE IN ('세단','SUV') # 자동차 종류 조건
AND TB1.CAR_TYPE = TB3.CAR_TYPE #JOIN
AND TB3.DURATION_TYPE LIKE '30%'
AND TB2.CAR_ID NOT IN 
(    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01')
GROUP BY TB2.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC