-- 코드를 입력하세요
SELECT TB2.ANIMAL_ID,TB2.ANIMAL_TYPE,TB2.NAME
FROM ANIMAL_INS TB1, ANIMAL_OUTS TB2
WHERE TB1.ANIMAL_ID = TB2.ANIMAL_ID
AND TB1.SEX_UPON_INTAKE LIKE 'Intact%' # 들어올때 중성화 안하고
AND (TB2.SEX_UPON_OUTCOME LIKE 'Spayed%' OR TB2.SEX_UPON_OUTCOME LIKE 'NEutered%')
ORDER BY 1
