-- 코드를 입력하세요
SELECT TB1.REST_ID,TB1.REST_NAME,TB1.FOOD_TYPE,TB1.FAVORITES,
TB1.ADDRESS,ROUND(AVG(TB2.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO TB1, REST_REVIEW TB2
WHERE TB1.REST_ID = TB2.REST_ID
AND TB1.REST_ID IN (
SELECT REST_ID 
FROM REST_INFO
WHERE ADDRESS LIKE '서울%')
GROUP BY TB1.REST_ID
ORDER BY 6 DESC, 4 DESC

