# -- 코드를 입력하세요
SELECT YEAR(TB2.SALES_DATE) AS YEAR,MONTH(TB2.SALES_DATE) AS MONTH,TB1.GENDER AS GENDER,COUNT(DISTINCT TB1.USER_ID) AS USERS
FROM USER_INFO TB1, ONLINE_SALE TB2
WHERE TB1.USER_ID = TB2.USER_ID
AND TB1.GENDER IS NOT NULL
GROUP BY YEAR(TB2.SALES_DATE),MONTH(TB2.SALES_DATE),TB1.GENDER
HAVING COUNT(*) > 0
ORDER BY 1 ASC,2 ASC,3 ASC
