-- 코드를 입력하세요
SELECT YEAR(TB2.SALES_DATE) AS YEAR, MONTH(TB2.SALES_DATE) AS MONTH,
COUNT(DISTINCT TB2.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT TB2.USER_ID) / (
SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) 
AS PUCHASED_RATIO
FROM USER_INFO TB1,ONLINE_SALE TB2
WHERE TB1.USER_ID = TB2.USER_ID
AND YEAR(TB1.JOINED) = 2021 /* 2021 가입 회원에 대해 */
GROUP BY YEAR(TB2.SALES_DATE), MONTH(TB2.SALES_DATE)
ORDER BY 1 ASC, 2 ASC