-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS, ROUND((COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)),1) AS PUCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE O
ON I.USER_ID = O.USER_ID AND YEAR(I.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE) , MONTH(O.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC