-- 코드를 입력하세요
SELECT TB1.NAME,TB1.DATETIME
FROM ANIMAL_INS TB1
WHERE TB1.ANIMAL_ID NOT IN
(SELECT TB2.ANIMAL_ID
FROM ANIMAL_OUTS TB2) # 입양 못간 동물이면 TB1에는 있지만 TB2에는 없는애를 골라야한다
ORDER BY TB1.DATETIME ASC # 오름차순(낮은거) -> 오래된순
LIMIT 3

