-- 코드를 입력하세요
SELECT TB2.PRODUCT_ID, TB1.PRODUCT_NAME, SUM(TB2.AMOUNT * TB1.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT TB1, FOOD_ORDER TB2
WHERE TB1.PRODUCT_ID = TB2.PRODUCT_ID
AND MONTH(TB2.PRODUCE_DATE) = 5 
AND YEAR(TB2.PRODUCE_DATE) = 2022
GROUP BY TB2.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC

