-- 코드를 입력하세요
# SET @HOUR = -1;
# SELECT (@HOUR := @HOUR + 1) AS HOUR,(SELECT COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR) AS COUNT
# FROM ANIMAL_OUTS
# WHERE @HOUR < 23

# SET @HOUR = -1; # 기본변수 세팅
# SELECT (@HOUR := @HOUR + 1) AS HOUR, (SELECT COUNT(*)
# FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME) = @HOUR) AS COUNT
# FROM ANIMAL_OUTS
# WHERE @HOUR < 23
# ORDER BY 1 ASC
SET @HOUR = -1;
SELECT (@HOUR := @HOUR + 1) AS HOUR, (SELECT COUNT(*)
                                      FROM ANIMAL_OUTS
                                      WHERE HOUR(DATETIME) = @HOUR
                                     ) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
ORDER BY 1 ASC