SELECT DISTINCT TB2.ID, TB2.EMAIL,TB2.FIRST_NAME, TB2.LAST_NAME
FROM SKILLCODES TB1, DEVELOPERS TB2
WHERE TB2.SKILL_CODE = (TB1.CODE | TB2.SKILL_CODE)
AND TB1.CATEGORY LIKE 'Front End'
ORDER BY 1 ASC
