-- 코드를 입력하세요
SELECT TB2.USER_ID AS USER_ID,TB2.NICKNAME AS NICKNAME, SUM(TB1.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD TB1, USED_GOODS_USER TB2
WHERE 1=1
AND TB1.STATUS = 'DONE'
AND TB1.WRITER_ID = TB2.USER_ID
GROUP BY TB2.USER_ID
HAVING SUM(TB1.PRICE) >= 700000
ORDER BY 3 ASC