-- 코드를 작성해주세요

SELECT TB2.EMP_NO,TB2.EMP_NAME,
CASE 
WHEN AVG(TB3.SCORE) >= 96 THEN 'S'
WHEN AVG(TB3.SCORE) >= 90 THEN 'A'
WHEN AVG(TB3.SCORE) >= 80 THEN 'B'
ELSE 'C'
END AS GRADE,
CASE 
WHEN AVG(TB3.SCORE) >= 96 THEN TB2.SAL * 0.2
WHEN AVG(TB3.SCORE) >= 90 THEN TB2.SAL * 0.15
WHEN AVG(TB3.SCORE) >= 80 THEN TB2.SAL * 0.1
ELSE 0
END AS BONUS
FROM HR_DEPARTMENT TB1, HR_EMPLOYEES TB2, HR_GRADE TB3
WHERE TB1.DEPT_ID = TB2.DEPT_ID
AND TB2.EMP_NO = TB3.EMP_NO
GROUP BY TB3.EMP_NO
ORDER BY 1 ASC


