-- 코드를 입력하세요
SELECT TB1.MEMBER_NAME, TB2.REVIEW_TEXT,DATE_FORMAT(TB2.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE 
FROM MEMBER_PROFILE TB1, REST_REVIEW TB2
WHERE TB1.MEMBER_ID = TB2.MEMBER_ID
AND TB1.MEMBER_ID =
(SELECT MEMBER_ID
 FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1)
ORDER BY 3 ASC, 2 ASC
