-- 코드를 작성해주세요
SELECT TB1.ITEM_ID,TB1.ITEM_NAME,TB1.RARITY
FROM ITEM_INFO TB1, ITEM_TREE TB2
WHERE TB1.ITEM_ID = TB2.ITEM_ID
AND TB2.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO
                   WHERE RARITY LIKE 'RARE')
ORDER BY 1 DESC
