-- 코드를 입력하세요
SELECT TB1.ANIMAL_ID,TB1.NAME
FROM ANIMAL_INS TB1, ANIMAL_OUTS TB2
WHERE TB1.ANIMAL_ID = TB2.ANIMAL_ID
AND TB1.DATETIME > TB2.DATETIME
ORDER BY TB1.DATETIME ASC
#입양일 TB2.DATETIME -> 빠르다는건 먼저니까 대소비교에선 작아야지
# 보호시작일 TB1.DATETIME