-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
AND YEAR(START_DATE) = 2022
AND CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
              WHERE MONTH(START_DATE) BETWEEN 8 AND 10
              AND YEAR(START_DATE) = 2022
              GROUP BY CAR_ID
              HAVING COUNT(*) >= 5) # 총대여횟수 5회 이상인 CAR_ID 추출하고
GROUP BY MONTH, CAR_ID #이후에 각 데이터에 대해 추출 
HAVING COUNT(*) >= 1 # 특정 월 대여 횟수 0인 조건 제외
ORDER BY MONTH ASC, CAR_ID DESC
