-- 코드를 입력하세요
SELECT MONTH(TB2.START_DATE) AS MONTH,TB2.CAR_ID, COUNT(*) AS RECORDS
FROM (
SELECT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID
HAVING COUNT(*) >= 5) TB1, CAR_RENTAL_COMPANY_RENTAL_HISTORY TB2
WHERE YEAR(TB2.START_DATE) = 2022
AND MONTH(TB2.START_DATE) BETWEEN 8 AND 10
AND TB1.CAR_ID = TB2.CAR_ID # 이렇게 하면 일단 5회 이상 충족하는 애들만 들어오게됨
GROUP BY MONTH(TB2.START_DATE),TB2.CAR_ID
ORDER BY 1 ASC, 2 DESC
