-- 코드를 작성해주세요
SELECT YEAR(TB1.DIFFERENTIATION_DATE) AS YEAR ,(TB2.SIZE_OF_COLONY - TB1.SIZE_OF_COLONY) AS YEAR_DEV,TB1.ID
FROM ECOLI_DATA TB1, (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)) TB2 #이렇게 하면 ID별 MAX값이 나온다.
WHERE YEAR(TB1.DIFFERENTIATION_DATE) = TB2.YEAR
ORDER BY 1 ASC , 2 ASC;

# SELECT YEAR(X.DIFFERENTIATION_DATE) AS YEAR, MAX(X.SIZE_OF_COLONY) AS SIZE_OF_COLONY 
# FROM ECOLI_DATA X
# GROUP BY YEAR(X.DIFFERENTIATION_DATE)