# -- 코드를 작성해주세요

select YEAR(a.DIFFERENTIATION_DATE) AS YEAR,
b.SIZE_OF_COLONY - a.SIZE_OF_COLONY AS YEAR_DEV,
 a.ID AS ID
from ECOLI_DATA a
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR ,MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) b
ON b.YEAR = YEAR(a.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC
