SELECT (SELECT ID FROM FISH_INFO WHERE a.FISH_TYPE = FISH_TYPE AND a.LENGTH = LENGTH) as ID,b.FISH_NAME as FISH_NAME, a.LENGTH AS LENGTH FROM (
SELECT FISH_TYPE,MAX(LENGTH) AS LENGTH FROM FISH_INFO
GROUP BY FISH_TYPE ) a , FISH_NAME_INFO b
WHERE a.FISH_TYPE = b.FISH_TYPE
ORDER BY ID ASC