-- 코드를 작성해주세요
SELECT SUM(TB3.SCORE) AS SCORE, TB3.EMP_NO AS EMP_NO,
TB2.EMP_NAME AS EMP_NAME,TB2.POSITION AS POSITION,TB2.EMAIL AS EMAIL
FROM HR_DEPARTMENT TB1, HR_EMPLOYEES TB2, HR_GRADE TB3
WHERE TB1.DEPT_ID = TB2.DEPT_ID
AND TB2.EMP_NO = TB3.EMP_NO
AND TB3.YEAR = 2022
GROUP BY TB3.EMP_NO
ORDER BY SUM(TB3.SCORE) DESC
LIMIT 1
