-- 코드를 입력하세요
SELECT TB2.INGREDIENT_TYPE AS INGREDIENT_TYPE, 
SUM(TB1.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF TB1, ICECREAM_INFO TB2
WHERE TB1.FLAVOR = TB2.FLAVOR
GROUP BY TB2.INGREDIENT_TYPE
ORDER BY 2 ASC