-- 코드를 입력하세요
SELECT TB1.CATEGORY AS CATEGORY, SUM(TB2.SALES) AS TOTAL_SALES
FROM BOOK TB1, BOOK_SALES TB2
WHERE TB1.BOOK_ID = TB2.BOOK_ID
AND YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
GROUP BY TB1.CATEGORY
ORDER BY 1 ASC
