-- 코드를 입력하세요
SELECT BOOKS.CATEGORY,SUM(SALE.SALES) AS TOTAL_SALES
FROM BOOK BOOKS
JOIN BOOK_SALES SALE
ON BOOKS.BOOK_ID =  SALE.BOOK_ID
WHERE YEAR(SALE.SALES_DATE) = 2022 AND MONTH(SALE.SALES_DATE) = 1
GROUP BY BOOKS.CATEGORY
ORDER BY BOOKS.CATEGORY ASC;