-- 코드를 입력하세요
SELECT TB1.BOOK_ID, TB2.AUTHOR_NAME, DATE_FORMAT(TB1.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK TB1, AUTHOR TB2
WHERE TB1.AUTHOR_ID = TB2.AUTHOR_ID
AND TB1.CATEGORY = '경제'
ORDER BY 3 ASC


